# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent
# io.openshift.expose-services="8080:http" \

LABEL io.k8s.description="A basic Apache HTTP Server child image, uses ONBUILD" \
      io.k8s.display-name="Apache HTTP Server" \
      io.openshift.tags="apache, httpd"
COPY myinfo.html /var/www/html

RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf
RUN sed -i "s/#ServerName www.example.com:80/ServerName 0.0.0.0:8080/g" /etc/httpd/conf/httpd.conf

RUN chgrp -R 0 /var/log/httpd /var/run/httpd \
    && chmod -R g=u /var/log/httpd /var/run/httpd

USER ex288u

EXPOSE 8080
